# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('present', models.BooleanField(help_text='Is the student present.')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
