# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:42
from __future__ import unicode_literals

import apps.school.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Student class code.', max_length=50)),
                ('school_year', models.CharField(help_text='School year in 2016-2017 format.', max_length=9, validators=[apps.school.utils.validate_school_year])),
                ('students', models.ManyToManyField(related_name='groups', to='school.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ignore_absence', models.BooleanField(default=False, help_text='Check this to ignore the absence reports, and lower the weight of the absence of the students. this is useful when this lesson is an extra lesson and only some students will follow it.')),
                ('start', models.DateTimeField(help_text='Start date and time of the lesson')),
                ('end', models.DateTimeField(help_text='End date and time of the lesson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='school_year',
            field=models.CharField(help_text='School year in 2016-2017 format.', max_length=9, validators=[apps.school.utils.validate_school_year]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.Course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(help_text='The group that got this lesson.', on_delete=django.db.models.deletion.CASCADE, to='school.Group'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(help_text='Select the teacher that is giving this lesson.', on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('code', 'school_year')]),
        ),
    ]
