# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_presence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=set([('lesson', 'student')]),
        ),
    ]
