# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_auto_20170516_1032'),
        ('school', '0003_uniqueness_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='absence_report',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='absence.AbsenceReport'),
        ),
    ]
