# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 10:50
from __future__ import unicode_literals

from django.db import migrations, models


def convert_counselors(apps, schema_editor):
	Counselor = apps.get_model('school', 'Counselor')
	Teacher = apps.get_model('school', 'Teacher')

	for counselor in Counselor.objects.all():
		try:
			teacher = Teacher.objects.get(user=counselor.user)
			teacher.is_counselor = True
			teacher.save()
		except:
			print('Skipping...')
			continue


class Migration(migrations.Migration):

	dependencies = [
		('school', '0004_relation_presence_to_report'),
	]

	operations = [
		migrations.AddField(
			model_name='teacher',
			name='is_counselor',
			field=models.BooleanField(default=False),
		),
		migrations.RunPython(convert_counselors),
		migrations.DeleteModel(
			name='Counselor',
		),
	]
