# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_counselor_migrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(default=None, max_length=128, null=True, unique=True),
        ),
    ]
