# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='counselor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.Teacher'),
        ),
    ]
