# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_relation_from_student_to_counselor'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProgressIndexPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('complete', models.BooleanField(default=False)),
                ('index', models.FloatField(default=None, null=True)),
                ('triggered', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_indexes', to='school.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='studentprogressindexpoint',
            unique_together=set([('student', 'month')]),
        ),
    ]
