# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_add_index_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
    ]
