# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_presence_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogressindexpoint',
            name='triggered_reason',
            field=models.CharField(choices=[('presence', 'Presence'), ('grade', 'Grade'), ('mixed', 'Mixed (Presence and grade)'), ('other', 'Other')], default=None, max_length=50, null=True),
        ),
    ]
