# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:09
from __future__ import unicode_literals

import apps.school.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_studentprogressindexpoint_triggered_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogressindexpoint',
            name='school_year',
            field=models.CharField(default='', help_text='School year in 2016-2017 format.', max_length=9, validators=[apps.school.validations.validate_school_year]),
        ),
        migrations.AlterUniqueTogether(
            name='studentprogressindexpoint',
            unique_together=set([('student', 'period', 'school_year')]),
        ),
    ]
