# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_from', models.DateTimeField(auto_now_add=True)),
                ('report_until', models.DateTimeField(default=None, null=True)),
                ('type', models.CharField(choices=[('sick', 'Sick'), ('family', 'Family Reasons'), ('other', 'Other Reasons')], max_length=50)),
                ('reason', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('closed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_reports_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_reports_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_reports', to='school.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
