# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_from', models.DateTimeField(auto_now_add=True)),
                ('report_until', models.DateTimeField(default=None, null=True)),
                ('type', models.CharField(choices=[('sick', 'Sick'), ('family', 'Family Reasons'), ('other', 'Other Reasons')], max_length=50)),
                ('reason', models.TextField(blank=True, default=None, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
