# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absence', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencereport',
            name='closed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_reports_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absencereport',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='absence_reports_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absencereport',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_reports', to='school.Student'),
        ),
    ]
